language: python
version: "3.6"

services:
  - docker

before_script: pip install docker-compose
script:
  - docker-compose run --rm app test rafinhas.tests.Fluxo &&
  - docker-compose run --rm app flake8
