language: python

sudo: required

services:
  - docker

before_script: 
  - sudo service postgresql stop
  - while lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose up -d
  - docker ps

script:
  - docker-compose run --rm app test rafinhas.tests.Fluxo && /
  - docker-compose run --rm app flake8
