language: python

sudo: required

services:
  - docker

before_script: 
  - docker-compose up -d
  - docker ps

script:
  - docker-compose run --rm app test rafinhas.tests.Fluxo &&
  - docker-compose run --rm app flake8
