version: '3'
volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rafinhas
      POSTGRES_PASSWORD: secret

  app:
    build:
      context: .
    image: rafinhas
    environment:
      DJANGO_DEBUG: 1
      DB_HOST: postgres
      DB_NAME: rafinhas
      DB_USER: rafinhas
      DB_PASSWORD: secret
      DB_PORT: 5432
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./application:/opt/application
    command: ['runserver', '0.0.0.0:8000']
