version: "3"

services:
  db:
    image: postgres
  application:
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes: 
      - ./application:/application
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db