# Generated by Django 2.2.3 on 2019-07-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
