# Generated by Django 2.2.3 on 2019-07-14 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Carro'),
        ),
    ]
