# Generated by Django 2.2.3 on 2019-07-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0003_auto_20190715_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('financas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Financas')),
            ],
        ),
        migrations.DeleteModel(
            name='Saida',
        ),
        migrations.AddField(
            model_name='cargo',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Funcionario'),
        ),
        migrations.AddField(
            model_name='formadepagamento',
            name='pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Pagamento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Servico'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Servico'),
        ),
        migrations.AddField(
            model_name='servico',
            name='pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='financas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Financas'),
        ),
    ]
