# Generated by Django 2.2.3 on 2019-07-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0004_auto_20190715_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='servico',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='papel',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Funcionario'),
        ),
        migrations.AddField(
            model_name='servico',
            name='operacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Operacao'),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
