# Generated by Django 2.2.3 on 2019-07-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0005_auto_20190715_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='funcionario',
            new_name='operador',
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='defeito',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='comentarios',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='comentarios',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Pagamento'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='saida',
            field=models.DateTimeField(null=True),
        ),
    ]
