# Generated by Django 2.2.3 on 2019-07-15 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0006_auto_20190715_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='financas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 17, 35, 59, 334396)),
        ),
    ]
