# Generated by Django 2.2.3 on 2019-07-15 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0007_financas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 17, 37, 14, 116453, tzinfo=utc)),
        ),
    ]
