# Generated by Django 2.2.3 on 2019-07-15 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0009_auto_20190715_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
