# Generated by Django 2.2.3 on 2019-07-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0010_auto_20190715_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defeito',
            name='carro',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Carro'),
        ),
    ]
