# Generated by Django 2.2.3 on 2019-07-15 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0011_auto_20190715_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='saida',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
