# Generated by Django 2.2.3 on 2019-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0012_auto_20190715_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='entrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
