# Generated by Django 2.2.3 on 2019-07-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0014_auto_20190717_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financas',
            new_name='Financa',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='financas',
            new_name='Financa',
        ),
        migrations.RenameField(
            model_name='retirada',
            old_name='financas',
            new_name='Financa',
        ),
    ]
