# Generated by Django 2.2.3 on 2019-07-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0015_auto_20190717_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financa',
            new_name='Transacao',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='Financa',
            new_name='transacao',
        ),
        migrations.RenameField(
            model_name='retirada',
            old_name='Financa',
            new_name='transacao',
        ),
    ]
