# Generated by Django 2.2.3 on 2019-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0016_auto_20190717_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='operacao',
        ),
        migrations.AddField(
            model_name='servico',
            name='operacao',
            field=models.ManyToManyField(null=True, to='rafinhas.Operacao'),
        ),
    ]
