# Generated by Django 2.2.3 on 2019-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0017_auto_20190722_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='operacao',
            field=models.ManyToManyField(to='rafinhas.Operacao'),
        ),
    ]
