# Generated by Django 2.2.3 on 2019-07-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0018_auto_20190722_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Cliente'),
        ),
        migrations.AddField(
            model_name='retirada',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafinhas.Funcionario'),
        ),
    ]
