# Generated by Django 2.2.3 on 2019-07-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafinhas', '0019_auto_20190722_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retirada',
            name='operador',
        ),
    ]
